export enum EDIT_FLAG { NO_CHANGE = 0, NEW, UPDATE, DELETE }
export enum COURSE_STATUS { PENDING = 0, PROCESSING = 1, COMPLETE = 2, CALCEL = 3 }
export enum COURSE_TYPE { ORDINARY = 1, INVITE, SPRINT }
export enum GENDER { FEMALE = 0, MALE = 1 }
export enum ORDER_TYPE { NEW = 1, RENEW, EXPERIENCE }
export enum ORDER_STATUS { NORMAL = 1, FROZEN, REFUNDING, REFUND }
// export enum ORDER_STATUS { NEW = 1, RENEW, COMPLETE, REFUND, FROZEN, INVALID }
export enum PAY_STATUS { UNPAY = 0, PAIED, FROZEN, REFUNDED }
export enum RELATIONSHIP { FATHER = 1, MOTHER, OTHER }



