server:
  port: 5201
spring:
  application:
    profiles:
      active: uat
  datasource:
    url: jdbc:mysql://47.100.242.85:6670/llsgzsuat?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: czy1377449!
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000

swagger.enabled: true
nmt.token.key: puatsdie11k4nsdf
nmt.token.expireMinute: 15
nmt.token.refreshMinute: 2